version: 1

update_configs:
  - package_manager: go:modules
    directory: /
    update_schedule: daily
    target_branch: dev

  - package_manager: github_actions
    directory: /
    update_schedule: daily
    target_branch: dev
