name: çreate tag

on:
  push:
    branches:
      - master
      
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - name: determine semantic release
      run: |
        curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ./semantic-release
        chmod u=rx,g=,o= ./semantic-release
        ./semantic-release -vf --token ${{ secrets.GITHUB_TOKEN }} --changelog .changelog
